author: garethflowers
description: Personal portfolio website of Gareth Flowers, Software Engineer.
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap
remote_theme: garethflowers/jekyll-simple-theme
social:
  name: Gareth Flowers
  links:
    - https://github.com/garethflowers
    - https://x.com/garethflowers
    - https://www.linkedin.com/in/garethflowers
tagline: Software Engineer
title: Gareth Flowers
twitter:
  username: garethflowers
  card: summary
