# ----------------------- #
# Site
# ----------------------- #

title: Gareth Flowers
author: Gareth Flowers
author_twitter: '@garethflowers'
author_location: England

# ----------------------- #
# Jekyll
# ----------------------- #

markdown: redcarpet
exclude:  [ Gemfile, Gemfile.lock, README.md, vendor/ ]
gems:
  - jekyll-sitemap
