# Site
author:
  location: England
  name: Gareth Flowers
avatar: https://secure.gravatar.com/avatar/5750e5553f140aa42f68c6bbefed6989
description: Full Stack Developer
title: Gareth Flowers
username:
  twitter: garethflowers
  github: garethflowers
layout: default

collections:
  projects:
    output: true

# Config
exclude:
  - Gemfile.lock
  - README.md
plugins:
  - jekyll-sitemap
markdown: kramdown
