author:
  location: England
  name: Gareth Flowers
description: Personal website of Gareth Flowers, Full Stack Developer.
layout: default
locale: en_GB
logo: https://secure.gravatar.com/avatar/5750e5553f140aa42f68c6bbefed6989
social:
  name: Gareth Flowers
  links:
    - https://github.com/garethflowers
    - https://twitter.com/garethflowers
tagline: Full Stack Developer
title: Gareth Flowers
twitter:
  username: garethflowers
  card: summary

collections:
  projects:
    output: true

exclude:
  - Gemfile.lock
  - README.md
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
remote_theme: garethflowers/jekyll-simple-theme
