# ----------------------- #
# Site
# ----------------------- #

title: Gareth Flowers
author: Gareth Flowers
author_twitter: '@garethflowers'
author_location: England

# ----------------------- #
# Jekyll
# ----------------------- #

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-sitemap
include:
  - .well-known
markdown: kramdown
