# ----------------------- #
# Site
# ----------------------- #

name: Gareth Flowers
url: garethflowers.me.uk

author: Gareth Flowers
author_twitter: '@garethflowers'
author_location: England

# ----------------------- #
# Jekyll
# ----------------------- #

markdown: redcarpet
gems:
  - jekyll-sitemap
