name: Build and Publish Images
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "*.*.*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Repos
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
            "https://api.github.com/user/repos" \
            | jq -c ".[] | select( .has_pages == true and .full_name != \"${{ github.repository }}\" )" \
            | jq -r ".full_name" \
            | while read REPO
          do
              echo "Update gh-pages $REPO"
              curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
                https://api.github.com/repos/$REPO/pages/builds \
                | jq ".status"
          done
